/**
 * 机械制造工艺学终极刷题库 V3 - 题库数据
 * 总计：98道题 (阶段1: 23单选+25判断 | 阶段2: 25单选+25判断)
 */
const questions = [
  // ==================== 阶段性测验(1) - 单选题 (1-23) ====================
  { id: 1, stage: 1, type: "single", question: "机械制造工艺学的核心研究内容是", options: ["机械设计方法", "机械加工与装配工艺", "材料力学性能", "机械传动原理"], answer: "B" },
  { id: 2, stage: 1, type: "single", question: "时间定额中直接改变工件尺寸的时间是", options: ["基本时间", "辅助时间", "工作地服务时间", "准备终结时间"], answer: "A" },
  { id: 3, stage: 1, type: "single", question: "加工经济精度指的是", options: ["最高精度", "最低精度", "正常加工可经济达到的精度", "理论精度"], answer: "C" },
  { id: 4, stage: 1, type: "single", question: "直接找正装夹的特点是", options: ["效率高", "精度高", "适合大批", "夹具复杂"], answer: "B" },
  { id: 5, stage: 1, type: "single", question: "大批量箱体零件常用的精基准是", options: ["底面", "侧面", "一面两孔", "主轴孔"], answer: "C" },
  { id: 6, stage: 1, type: "single", question: "长V形块定位限制的自由度数为", options: ["2", "3", "4", "5"], answer: "C" },
  { id: 7, stage: 1, type: "single", question: "外圆 IT5、Ra0.04µm 的加工路线通常是", options: ["粗车-半精车", "粗车-半精车-粗磨", "粗车-半精车-粗磨-精磨-研磨", "粗车-精车"], answer: "C" },
  { id: 8, stage: 1, type: "single", question: "大批量高精度配合件常用装配方法是", options: ["完全互换", "分组选配", "修配", "调整"], answer: "B" },
  { id: 9, stage: 1, type: "single", question: "表面粗糙度降低,零件的耐疲劳性", options: ["提高", "降低", "不变", "不确定"], answer: "A" },
  { id: 10, stage: 1, type: "single", question: "加工误差统计分析中,常用的分布曲线是", options: ["直线分布", "正态分布", "抛物线分布", "折线分布"], answer: "B" },
  { id: 11, stage: 1, type: "single", question: "常值系统误差的特点是", options: ["随机变化", "大小方向固定", "随时间线性变", "无规律"], answer: "B" },
  { id: 12, stage: 1, type: "single", question: "磨削加工时,一般采用的砂轮粒度(), Ra越小。", options: ["越小", "越大", "不一定", "没区别"], answer: "B" },
  { id: 13, stage: 1, type: "single", question: "零件表面质量不包括", options: ["表面粗糙度", "表面残余应力", "零件重量", "表面冷作硬化"], answer: "C" },
  { id: 14, stage: 1, type: "single", question: "加工表面冷作硬化产生的主要原因是", options: ["切削热作用", "金属塑性变形", "刀具磨损", "机床振动"], answer: "B" },
  { id: 15, stage: 1, type: "single", question: "对加工精度影响最大的热源是传给()的热量。", options: ["刀具", "工件", "切屑", "空气"], answer: "B" },
  { id: 16, stage: 1, type: "single", question: "粗基准一般不允许重复使用,主要原因是", options: ["毛坯表面精度低", "提高效率", "简化夹具", "减少余量"], answer: "A" },
  { id: 17, stage: 1, type: "single", question: "机械制造中最常用的夹紧机构是", options: ["斜楔", "螺旋", "偏心", "铰链"], answer: "B" },
  { id: 18, stage: 1, type: "single", question: "选择精基准时,采用设计基准作为定位基准符合", options: ["统一基准", "基准重合", "互为基准", "自为基准"], answer: "B" },
  { id: 19, stage: 1, type: "single", question: "钻床夹具的导向元件是", options: ["定位销", "钻套", "对刀块", "定向键"], answer: "B" },
  { id: 20, stage: 1, type: "single", question: "加工箱体类零件,经常采用一面两销定位,其中一个菱形销可以约束()个自由度。", options: ["1", "2", "3", "4"], answer: "A" },
  { id: 21, stage: 1, type: "single", question: "传统的车、铣、刨、磨、钻属于", options: ["去除加工", "结合加工", "变形加工", "热加工"], answer: "A" },
  { id: 22, stage: 1, type: "single", question: "采用试切法加工零件时,产生加工误差的主要原因是", options: ["机床误差", "测量误差", "刀具磨损", "调整误差"], answer: "D" },
  { id: 23, stage: 1, type: "single", question: "下列适合加工非铁金属的外圆表面的加工路线是", options: ["粗车-半精车-粗磨-精磨", "粗车-半精车-精车-金刚石车", "粗镗-半精镗-精镗-金刚镗", "粗铣-半精铣-粗磨-精磨"], answer: "B" },

  // ==================== 阶段性测验(1) - 判断题 (24-48) ====================
  { id: 24, stage: 1, type: "judge", question: "工艺系统由机床、夹具、刀具和工件四部分组成。", options: ["正确", "错误"], answer: "A" },
  { id: 25, stage: 1, type: "judge", question: "生产类型可分为单件小批生产、成批生产、大批大量生产三类。", options: ["正确", "错误"], answer: "A" },
  { id: 26, stage: 1, type: "judge", question: "基准分为设计基准和工艺基准两大类。", options: ["正确", "错误"], answer: "A" },
  { id: 27, stage: 1, type: "judge", question: "工艺尺寸链中封闭环是人为直接加工保证的尺寸。", options: ["正确", "错误"], answer: "B" },
  { id: 28, stage: 1, type: "judge", question: "工序安排应遵循基准先行、先粗后精、先面后孔的原则。", options: ["正确", "错误"], answer: "A" },
  { id: 29, stage: 1, type: "judge", question: "加工精度仅指零件的尺寸精度,不包括形状和位置精度。", options: ["正确", "错误"], answer: "B" },
  { id: 30, stage: 1, type: "judge", question: "调整误差是试切或调整加工产生的误差。", options: ["正确", "错误"], answer: "A" },
  { id: 31, stage: 1, type: "judge", question: "工艺基准包括定位、测量、装配、工序基准。", options: ["正确", "错误"], answer: "A" },
  { id: 32, stage: 1, type: "judge", question: "工步要求加工表面、刀具、切削用量均不变。", options: ["正确", "错误"], answer: "B" },
  { id: 33, stage: 1, type: "judge", question: "导轨扭曲会导致工件圆柱度误差。", options: ["正确", "错误"], answer: "A" },
  { id: 34, stage: 1, type: "judge", question: "装配精度完全由零件加工精度决定。", options: ["正确", "错误"], answer: "B" },
  { id: 35, stage: 1, type: "judge", question: "钻套分为固定、可换、快换三类。", options: ["正确", "错误"], answer: "A" },
  { id: 36, stage: 1, type: "judge", question: "常值系统误差可通过尺寸调整消除。", options: ["正确", "错误"], answer: "A" },
  { id: 37, stage: 1, type: "judge", question: "走刀是一个工步内的多次切削。", options: ["正确", "错误"], answer: "A" },
  { id: 38, stage: 1, type: "judge", question: "不完全定位在加工中是不允许的。", options: ["正确", "错误"], answer: "B" },
  { id: 39, stage: 1, type: "judge", question: "设计基准是工艺过程使用的基准。", options: ["正确", "错误"], answer: "B" },
  { id: 40, stage: 1, type: "judge", question: "专用夹具为特定工序专门设计。", options: ["正确", "错误"], answer: "A" },
  { id: 41, stage: 1, type: "judge", question: "主轴径向跳动会造成工件圆度误差。", options: ["正确", "错误"], answer: "A" },
  { id: 42, stage: 1, type: "judge", question: "机床夹具能保证精度、提高效率。", options: ["正确", "错误"], answer: "A" },
  { id: 43, stage: 1, type: "judge", question: "随机误差可以通过多次加工消除。", options: ["正确", "错误"], answer: "B" },
  { id: 44, stage: 1, type: "judge", question: "积屑瘤能保护刀具,所以在任何加工情况下都应让积屑瘤存在。", options: ["正确", "错误"], answer: "B" },
  { id: 45, stage: 1, type: "judge", question: "误差复映系数与工艺系统刚度成反比,刚度越大,误差复映系数越小。", options: ["正确", "错误"], answer: "A" },
  { id: 46, stage: 1, type: "judge", question: "机械加工精度包含尺寸精度、形状精度和位置精度。", options: ["正确", "错误"], answer: "A" },
  { id: 47, stage: 1, type: "judge", question: "零件表面存在残余拉应力时,可延长零件的疲劳寿命。", options: ["正确", "错误"], answer: "B" },
  { id: 48, stage: 1, type: "judge", question: "采用分组装配法时,零件的分组数越多,装配精度就越高,所以分组数越多越好。", options: ["正确", "错误"], answer: "B" },

  // ==================== 阶段性测验(2) - 单选题 (49-73, 原题号1-25) ====================
  { id: 49, stage: 2, type: "single", question: "表面残余拉应力会使疲劳强度", options: ["提高", "降低", "不变", "不确定"], answer: "B" },
  { id: 50, stage: 2, type: "single", question: "在一次装夹中,工件相对于刀具所占的每一个位置称为", options: ["工位", "工序", "工步", "行程"], answer: "A" },
  { id: 51, stage: 2, type: "single", question: "机床主轴回转误差中,对工件圆度误差影响最大的是", options: ["径向圆跳动", "轴向窜动", "倾角摆动", "温度变形"], answer: "A" },
  { id: 52, stage: 2, type: "single", question: "切削加工时,工件热变形最明显的零件是", options: ["粗大轴类", "细长轴类", "盘类零件", "箱体零件"], answer: "B" },
  { id: 53, stage: 2, type: "single", question: "夹具的核心组成部分,用于确定工件位置的元件是", options: ["夹紧元件", "定位元件", "导向元件", "夹具体"], answer: "B" },
  { id: 54, stage: 2, type: "single", question: "工件加工时,不需要限制全部6个自由度的定位方式称为", options: ["完全定位", "不完全定位", "过定位", "欠定位"], answer: "B" },
  { id: 55, stage: 2, type: "single", question: "加工余量是指加工过程中从被加工表面切除的", options: ["金属层厚度", "毛坯总厚度", "零件尺寸公差", "形位误差值"], answer: "A" },
  { id: 56, stage: 2, type: "single", question: "在工艺尺寸链计算中,增环尺寸增大将使封闭环尺寸", options: ["增大", "减小", "不变", "无规律变化"], answer: "A" },
  { id: 57, stage: 2, type: "single", question: "夹紧力方向应优先朝向", options: ["主要定位面", "加工面", "夹具侧面", "工件重心"], answer: "A" },
  { id: 58, stage: 2, type: "single", question: "高速加工速度比常规加工", options: ["高5-10倍", "高1-2倍", "低5-10倍", "低1-2倍"], answer: "A" },
  { id: 59, stage: 2, type: "single", question: "组合夹具的主要特点是", options: ["专用", "元件可重复使用", "适合大批", "结构固定"], answer: "B" },
  { id: 60, stage: 2, type: "single", question: "六点定位原理中,一个定位支承点可限制工件的自由度数量为", options: ["1", "2", "3", "6"], answer: "A" },
  { id: 61, stage: 2, type: "single", question: "欠定位是指", options: ["限制过多", "必须限制的自由度未限制", "完全定位", "不完全定位"], answer: "B" },
  { id: 62, stage: 2, type: "single", question: "下列不属于提高精度途径的是", options: ["减少原始误差", "误差补偿", "误差转移", "加加大切削用量"], answer: "D" },
  { id: 63, stage: 2, type: "single", question: "正态分布描述的是", options: ["常值系统误差", "变值系统误差", "随机误差", "原理误差"], answer: "C" },
  { id: 64, stage: 2, type: "single", question: "加工余量是指从工件表面切除的", options: ["体积", "材料层厚度", "质量", "面积"], answer: "B" },
  { id: 65, stage: 2, type: "single", question: "偏心夹紧适用于", options: ["切削力大", "振动大", "切削平稳中小批量", "精密加工"], answer: "C" },
  { id: 66, stage: 2, type: "single", question: "磨削加工时,一般采用的砂轮粒度(),Ra越小。", options: ["越小", "越大", "不一定", "没区别"], answer: "B" },
  { id: 67, stage: 2, type: "single", question: "工序集中的主要优点是", options: ["工序多", "设备简单", "装夹次数少", "适合小批量"], answer: "C" },
  { id: 68, stage: 2, type: "single", question: "轴类零件最常用的统一精基准是", options: ["外圆", "两端中心孔", "端面", "台阶面"], answer: "B" },
  { id: 69, stage: 2, type: "single", question: "加工表面、切削刀具、切削速度和进给量都不变的情况下所完成的工位内容,称为", options: ["安装", "工步", "工位", "走刀"], answer: "B" },
  { id: 70, stage: 2, type: "single", question: "夹紧力确定不正确的是", options: ["夹紧力应平行指向主要定位面", "夹紧力方向应与切削力、工件重力方向一致", "夹紧力作用点应处于工件刚度较好的部位", "夹紧力作用点应尽量靠近加工面"], answer: "A" },
  { id: 71, stage: 2, type: "single", question: "实体件上,粗加工圆形孔,批量生产,下面合适的加工方法是", options: ["车削", "铣削", "刨削", "钻削"], answer: "D" },
  { id: 72, stage: 2, type: "single", question: "大批大量生产的工艺特点错误的是", options: ["广泛采用专用的机床,流水线或自动线布置", "采用划线找正装夹", "对操作工人的技术水平要求较低", "要详细制定工艺规程"], answer: "B" },
  { id: 73, stage: 2, type: "single", question: "以下属于表面微观几何形状误差的是", options: ["表面波纹度", "宏观几何形状误差", "表面粗糙度", "表面位置误差"], answer: "C" },

  // ==================== 阶段性测验(2) - 判断题 (74-98, 原题号26-50) ====================
  { id: 74, stage: 2, type: "judge", question: "磨削易产生表面烧伤与残余应力。", options: ["正确", "错误"], answer: "A" },
  { id: 75, stage: 2, type: "judge", question: "夹紧机构一般不要求自锁。", options: ["正确", "错误"], answer: "B" },
  { id: 76, stage: 2, type: "judge", question: "粗基准是采用毛坯未加工表面作定位基准。", options: ["正确", "错误"], answer: "A" },
  { id: 77, stage: 2, type: "judge", question: "斜楔自锁条件是楔角大于两摩擦角之和。", options: ["正确", "错误"], answer: "B" },
  { id: 78, stage: 2, type: "judge", question: "假废品是测量超差但实际合格的工件。", options: ["正确", "错误"], answer: "A" },
  { id: 79, stage: 2, type: "judge", question: "辅助支承不限制自由度,只提高刚度。", options: ["正确", "错误"], answer: "A" },
  { id: 80, stage: 2, type: "judge", question: "工位是一次装夹内工件所占的每个加工位置。", options: ["正确", "错误"], answer: "A" },
  { id: 81, stage: 2, type: "judge", question: "单件生产使用通用夹具和详细工艺文件。", options: ["正确", "错误"], answer: "B" },
  { id: 82, stage: 2, type: "judge", question: "表面残余压应力有利于提高零件的疲劳强度。", options: ["正确", "错误"], answer: "A" },
  { id: 83, stage: 2, type: "judge", question: "表层金属的冷作硬化能够阻止疲劳裂纹的生长。", options: ["正确", "错误"], answer: "A" },
  { id: 84, stage: 2, type: "judge", question: "支承钉、支承板属于夹具中的定位元件。", options: ["正确", "错误"], answer: "A" },
  { id: 85, stage: 2, type: "judge", question: "欠定位在机械加工工艺中是允许经常采用的。", options: ["正确", "错误"], answer: "B" },
  { id: 86, stage: 2, type: "judge", question: "工件定位误差由基准不重合误差和基准位移误差两部分组成。", options: ["正确", "错误"], answer: "A" },
  { id: 87, stage: 2, type: "judge", question: "装配尺寸链的封闭环通常是装配最终要保证的装配精度。", options: ["正确", "错误"], answer: "A" },
  { id: 88, stage: 2, type: "judge", question: "装配工艺系统图可以清晰表达产品装配层次和先后顺序。", options: ["正确", "错误"], answer: "A" },
  { id: 89, stage: 2, type: "judge", question: "大批大量生产采用专用设备与互换装配。", options: ["正确", "错误"], answer: "A" },
  { id: 90, stage: 2, type: "judge", question: "互为基准常用于表面淬火工件。", options: ["正确", "错误"], answer: "A" },
  { id: 91, stage: 2, type: "judge", question: "夹紧力方向应垂直于导向面。", options: ["正确", "错误"], answer: "B" },
  { id: 92, stage: 2, type: "judge", question: "分组选配法是将零件按尺寸分组,同组互换。", options: ["正确", "错误"], answer: "A" },
  { id: 93, stage: 2, type: "judge", question: "成组技术能扩大批量,提高中小批生产效率。", options: ["正确", "错误"], answer: "A" },
  { id: 94, stage: 2, type: "judge", question: "在机械加工中,提高加工精度的方法只有提高机床精度这一种途径。", options: ["正确", "错误"], answer: "B" },
  { id: 95, stage: 2, type: "judge", question: "生产纲领是指企业在计划期内应当生产的产品产量和进度计划。", options: ["正确", "错误"], answer: "A" },
  { id: 96, stage: 2, type: "judge", question: "磨削淬火钢时,若磨削温度过高,会使表面产生烧伤。", options: ["正确", "错误"], answer: "A" },
  { id: 97, stage: 2, type: "judge", question: "表面层的冷作硬化会使零件表面硬度提高,同时也会降低零件的疲劳强度。", options: ["正确", "错误"], answer: "B" },
  { id: 98, stage: 2, type: "judge", question: "机械加工表面质量只包括表面粗糙度。", options: ["正确", "错误"], answer: "B" }
];